server:
  port: 8090
spring:
  application:
    name: service-swagger
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
zuul:
  routes:
    service-provider:
      path: /service-provider/** # 配置路由规则
    service-consumer:
      path: /service-consumer/** # 配置路由规则