server:
  port: 8050
spring:
  application:
    name: service-weather
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
redis:
  database: 0   #Redis数据库索引（默认为0）
  host: localhost   #Redis服务器地址
  port: 6379    #Redis服务器连接端口
pool:
  max-active: 200   #连接池最大连接数（使用负值表示没有限制）
  max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
  max-idel: 10    #连接池中的最大空闲连接
  min-idel: 0   #连接池中的最小空闲连接
  timeout: 1000   #连接超时时间（毫秒）
